### ISSUE TITLE
Развернуть BE и FE на машине (доступно из интернета)

### ISSUE THREAD

**Issue by AVLapina** [skondurushkin/ilp#32]

**Comment by skondurushkin** [comment]
Сделано
есть две VM
- Выделенная по запросу в SD
   IP: 158.160.52.140
   Доступ: по http
   Ссылка: http://158.160.52.140:3000/sign-in
- Выделенная мне лично
  IP: 158.160.62.120
  HostName: loyalty.devtst.ru
  Доступ: по http и https
  Ссылка: https://loyalty.devtst.ru/sign-in

На обеих настроена сборка и git
