### ISSUE TITLE
backend bugfixing 20230404

### ISSUE THREAD

**Issue by skondurushkin** [skondurushkin/ilp#67]
1. Метод создания article POST /api/ilp/article не сохраняет переданную цену.
{
  "code": "t-shirt-S",
  "name": "Черная футболка с логотипом компании, женская, S",
  "description": "Черная футболка с логотипом компании, женская, S",
  "price": 10,
  "available": true
}
2. Для article через АПИ нельзя добавить, изменить ссылку на картинку.
3. Создать, изменить, удалить article может пользователь без админских прав.
4. Метод POST /api/ilp/articles не работает сортировка по полю price. Если указать amount, то работает. Все таки что оставляем price или amount? Если amount, то может в БД поля таблиц articles, activities переименовать и атрибуты в АПИ чтобы не путаться?
{
  "page": 0,
  "pageSize": 5,
  "config": {
    "sort": [
      {
        "colName": "price",
        "sortType": "ASC"
      }
    ],
    "globalFilter": "string"
  }
}
5. В методах не работает поиск по globalFilter
POST /api/ilp/articles 
POST /api/ilp/activities
POST /api/ilp/profiles

6. В методах ниже, когда ничего не найдено возвращается ошибка с кодом 401.  
GET /api/ilp/article/search?search_key=12
GET /api/ilp/activity/search?search_key=12
GET /api/ilp/profile/search?search_key=12

7. Для activity через АПИ нельзя добавить, изменить start_date, end_date.
8. Создать, изменить, удалить activity может пользователь без админских прав.
9. Создать, изменить setting может пользователь без админских прав.

продолжение ниже

**Comment by skondurushkin** [comment]
тело для п 5 POST /api/ilp/articles 
```
{
  "page": 0,
  "pageSize": 5,
  "config": {
    "sort": [
      {
        "colName": "id",
        "sortType": "ASC"
      }
    ],
    "globalFilter": "кружка"
  }
}

```
тело для п 5 POST /api/ilp/activities
```
{
  "page": 0,
  "pageSize": 5,
  "config": {
    "sort": [
      {
        "colName": "name",
        "sortType": "ASC"
      }
    ],
    "globalFilter": "сотр"
  }
}
```

тело для п 5 POST /api/ilp/profiles
```
{
  "page": 0,
  "pageSize": 3,
  "config": {
    "sort": [
      {
        "colName": "id",
        "sortType": "ASC"
      }
    ],
    "globalFilter": "Иван"
  }
}

```

**Comment by mazutka** [comment]
10. Метод POST /api/ilp/wallet/write-off/4 с телом {"articleId": 1} возвращает ошибку:

List of constraint violations:[
        ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=orderStatus, rootBeanClass=class 
ru.itone.ilp.persistence.entities.WriteOff, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
[](url)

[Log_ilp_server.txt](https://github.com/skondurushkin/ilp/files/11148848/Log_ilp_server.txt)

11. Начисление и списание может сделать пользователь без админских прав.
POST /api/ilp/wallet/accrual/4
POST /api/ilp/wallet/write-off/4

12. Изменить статус заказа может пользователь без админских прав PATCH /api/ilp/wallet/write-off/4
13. Посмотреть историю операций другого пользователя, историю начислений, списаний может пользователь без админских прав. 
POST /api/ilp/wallet/history/2
POST /api/ilp/wallet/accruals/4
POST /api/ilp/wallet/write-offs/4

14. Не работают методы ниже. Локализовать ошибку не получилось. Для пользователя с админскими правами и корректным телом выдает 401 ошибку.
POST /api/ilp/wallet/write-offs/4
POST /api/ilp/wallet/write-offs
POST /api/ilp/wallet/accruals/4
POST /api/ilp/wallet/accruals
